CREATE DATABASE MADHUSHREE_PROJECT;
USE MADHUSHREE_PROJECT;
CREATE TABLE STUDENT
(
ROLL INT,
NAME VARCHAR(50),
SUBJECT VARCHAR(50),
MARKS INT,
CITY VARCHAR(50)
);
INSERT INTO STUDENT VALUES
(1,'RAHUL','PYTHON',85,'HOWRAH'),
(2,'PRIYA','SQL',92,'KOLKATA'),
(3,'AMIT','PYTHON',38,'HOWRAH'),
(4,'SNEHA','SQL',76,'DANKUNI'),
(5,'ROHAN','PYTHON',65,'KOLKATA'),
(6,'ANJALI','POWER BI',88,'HOWRAH'),
(7,'SAYAN','SQL',45,'KOLKATA'),
(8,'POOJA','PYTHON',95,'HOWRAH'),
(9,'KARAN','POWER BI',33,'KOLKATA'),
(10,'RIYA','SQL',71,'HOWRAH');
SELECT * FROM STUDENT;
CREATE VIEW PASS_STUDENT AS
SELECT ROLL,NAME,SUBJECT,MARKS FROM STUDENT WHERE MARKS>=40;
GO
SELECT * FROM PASS_STUDENT;
CREATE VIEW SUBJECT_AVERAGE AS
SELECT SUBJECT, AVG(MARKS) AS AVG_MARKS FROM STUDENT GROUP BY SUBJECT;
GO
SELECT * FROM SUBJECT_AVERAGE;